layout_spectrum: 0
color:
  saturation: 0.3387097
  lightness: 0.4856631
  brandStrength: 0.5053763
  brandColors:
    - '#171516'
    - '#FFFFFF'
    - '#6E655C'
    - '#A3C5F2'
    - '#FFEEA6'
  rhythmicContrast: 0.5770437
typography_spectrum: 0.3655914
name: Feliphe
